[package]
name = "SocialR"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
http-body-util = "0.1.0-rc.2"
thiserror = "1.0"
async-trait = "0.1"
log = "0.4"
futures = "0.3"
tokio-stream = "0.1"
